# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://a.geek.cl/"
defaultContentLanguage = "es"

enableRobotsTXT = true
paginate = 10
summaryLength = 15

[list]
showSummary = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
 post = "/:slug/"
 pagina = "/pagina/:title/" 

#[frontmatter]
 #date = [":filename", ":default", ":fileModTime"]

[frontmatter]
  date = [":filename", ":default"] 
